### ISSUE TITLE
Add example how users can change kernel list and add custom kernels

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/plasticparcels#21]
The first two examples provided focus on the ease of running simulations from different initialisation fields. That is an important aspect of plasticparcels.

However, the other key feature is for the testing of parameterisations. So we should add an example on how users can change the kernel list, and also add their own kernels

**Comment by michaeldenes** [comment]
This has been fixed in #32 for varying parameters and creating custom kernels, and in #29 for running simulations from different initialisation maps.
